FROM openjdk:17-jdk

WORKDIR /app


COPY target/The-Home-Services-Booking-System-0.0.1-SNAPSHOT.jar /app/The-Home-Services-Booking-System.jar

EXPOSE 8080

CMD ["java" ,"-jar", "The-Home-Services-Booking-System.jar"]
