---
- name: Deploy Backend Application
  hosts: localhost
  tasks:
    - name: Ensure Docker network exists
      command: docker network inspect homemate-network >/dev/null 2>&1 || docker network create homemate-network

    - name: Pull the latest Docker image for Backend
      command: docker pull {{ DOCKER_IMAGE }}

    - name: Stop and remove any running instance of the backend container
      command: docker ps -q --filter "name={{ DOCKER_CONTAINER }}" | grep -q . && docker stop {{ DOCKER_CONTAINER }} || true

    - name: Remove old backend container
      command: docker ps -aq --filter "name={{ DOCKER_CONTAINER }}" | grep -q . && docker rm {{ DOCKER_CONTAINER }} || true

    - name: Run backend container
      command: docker run -d --restart always --name {{ DOCKER_CONTAINER }} --network homemate-network -p 8080:8080 {{ DOCKER_IMAGE }}

