- name: Deploy Frontend Application
  hosts: localhost
  tasks:
    - name: Ensure Docker network exists
      shell: |
        docker network inspect homemate-network >/dev/null 2>&1 || docker network create homemate-network
      ignore_errors: yes

    - name: Create Docker network if it does not exist
      command: docker network create homemate-network
      when: ansible_facts['docker_networks']['homemate-network'] is not defined

    - name: Pull the latest Docker image for Frontend
      command: docker pull {{ REACT_APP_IMAGE }}

    - name: Stop and remove any running instance of the frontend container
      command: docker ps -q --filter "name=react-frontend" | grep -q . && docker stop react-frontend || true

    - name: Remove old frontend container
      command: docker ps -aq --filter "name=react-frontend" | grep -q . && docker rm react-frontend || true

    - name: Run frontend container
      command: docker run --pull=always -d --restart always --name react-frontend --network homemate-network -p 3000:3000 {{ REACT_APP_IMAGE }}
